route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:465'
        auth_username: 'USERNAME_HERE'
        auth_password: "PASSWORD_HERE"
        from: 'EMAIL_SENDER'
        to: 'EMAIL_RECIEVER'